---
title: "git_00"
author: "Ashley Saunders"
date: "Year 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

'Twas brillig, and the slithy toves

Did gyre and gimble in the wabe;

All mimsy were the borogoves,

And the mome raths outgrabe.

"Beware the Jabberwock, my son!"

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,

And sorry I could not travel both

And be one traveler, long I stood

And looked down one as far as I could

To where it bent in the undergrowth;

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,   
Shining with all his might:   
He did his very best to make   
The billows smooth and bright—   
And this was odd, because it was   
The middle of the night.   
   
The walrus and the carpenter   
Were walking close at hand;    
They wept like anything to see    
Such quantities of sand:   
“If this were only cleared away,”   
They said, “it would be grand!”   

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Hope is the thing with feathers    
That perches in the soul,    
And sings the tune without the words,    
And never stops at all,    
     
And sweetest in the gale is heard;    
And sore must be the storm     
That could abash the little bird    
That kept so many warm.      
     
I've heard it in the chillest land,    
And on the strangest sea;    
Yet, never, in extremity,    
It asked a crumb of me.    
